title: Daramola Oladunni Data Analytics portfolio
logo: IMG_8435.jpeg
description: A Result‑driven Data Analyst with 2 years of hands‑on experience using SQL for data interrogation and manipulation, Excel, and Power BI to transform raw data into clear, actionable insights. Skilled in data cleaning, analysing, and visualising complex datasets to support business decisions and improve operational performance. Proven ability to build interactive dashboards, automate reporting processes, and communicate findings that drive measurable results.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
